name: SapphireFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.2
description: Plugin for SapphireFreedom, an all-op server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, Prozza, iDelRey, falceso, DarkGamingDronze, tylerhyperHD, Hockeyfan360, AwesomePinch, Alco_Rs11, reuben4545]

# plugin.yml is no longer used to define commands.
